{% set name = "tenacity" %}
{% set version = "6.3.1" %}
{% set sha256 = "e14d191fb0a309b563904bbc336582efe2037de437e543b38da749769b544d7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv .
  noarch: python

requirements:
  host:
    - python >=3
    - pbr
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3
    - six >=1.9.0

test:
  imports:
    - tenacity

about:
  home: http://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works

  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: http://tenacity.readthedocs.io
  dev_url: http://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
    - xylar
